spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: cars
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/antigaspi
    username: user
    password: password

server:
  port: 8081

  flyway:
    enabled: true
    validate-on-migrate: true
